(function () {
  'use strict';
  const pair = (zh, en) => ({zh, en});
  const entry = (id, category, sourceIds, question, answer, keywords, related = []) =>
    ({id, category, sourceIds, question, answer, keywords, related});
  const categories = [
    {id: 'start', label: pair('了解服务', 'Getting started')},
    {id: 'xhs', label: pair('小红书推广', 'Xiaohongshu')},
    {id: 'local', label: pair('Local Market', 'Local Market')},
    {id: 'build', label: pair('网站、电商与 App', 'Websites, stores & apps')},
    {id: 'automation', label: pair('CRM 与自动化', 'CRM & automation')},
    {id: 'working', label: pair('报价与合作', 'Working together')}
  ];
  const entries = [
    entry('overview', 'start', ['overview'], pair('你们提供哪些服务？', 'What can Go Marketing help with?'),
      pair('我们提供中英文营销、小红书推广与代运营、网站和电商支持，以及 App、CRM 和业务自动化搭建。可以只从你目前最需要改善的一项开始，不必同时购买所有服务。',
        'We support bilingual marketing, Xiaohongshu promotion and account management, websites, ecommerce, apps, CRM and business automation. You can start with one priority; you do not need to purchase every service.'),
      ['做什么', '哪些服务', '什么服务', '业务范围', 'services', 'go marketing', 'what do you do'], ['start', 'quote']),
    entry('start', 'start', ['marketing-start'], pair('还没确定需要什么服务，能先咨询吗？', 'Can I enquire before deciding on a service?'),
      pair('可以。先告诉我们你的业务类型，以及最想改善的问题，例如新客不够、网站咨询少或跟进容易遗漏。团队会帮助你确定优先方向，不需要先准备完整方案。',
        'Yes. Tell us what your business does and what you would like to improve, such as discovery, website enquiries or missed follow-up. The team can help identify a starting point; a complete brief is not required.'),
      ['不知道', '不确定', '怎么开始', '从哪里开始', '餐厅', '获客', '生意', 'cafe', 'restaurant', 'where to start', 'not sure'], ['xhs-routes', 'crm']),
    entry('xhs-routes', 'xhs', ['xhs-routes'], pair('小红书有哪两种合作方式？', 'What are the two Xiaohongshu options?'),
      pair('一种是代运营你自己的账号，围绕品牌持续经营内容；另一种是在 Go Marketing 的公司账号上推广你的业务或活动。团队会根据推广目标、现有账号和素材情况，建议合适的方式。',
        'We can manage content on your own account, or promote your business or event through the Go Marketing company channel. The team can recommend a route based on your objective, existing account and available content.'),
      ['小红书', '两种', '区别', 'xiaohongshu', 'rednote', 'xhs', 'promotion options'], ['management', 'channel']),
    entry('management', 'xhs', ['management'], pair('自己的小红书账号可以交给你们管理吗？', 'Can you manage my own Xiaohongshu account?'),
      pair('可以。内容以你的 brief 或双方确认的计划为基础，发布前需要确认。发帖数量、周期、拍摄、私信支持和报告范围会在方案中列明，并非默认包含无限修改或全天候客服。',
        'Yes. Content follows your brief or an agreed plan and needs approval before publishing. Post volume, term, production, inbox support and reporting are scoped in the proposal, rather than unlimited revisions or round-the-clock support.'),
      ['代运营', '自己账号', '自己的账号', '账号管理', 'account management', 'manage my account', 'manage our account'], ['revisions', 'management-reports']),
    entry('channel', 'xhs', ['xhs-routes', 'reports'], pair('可以直接在你们的账号上推广吗？', 'Can you promote us through your company channel?'),
      pair('可以通过我们的公司账号介绍你的业务、产品或活动。这类推广套餐包含基础报告；具体篇数、内容、发布时间和费用，由团队根据需求确认。',
        'We can introduce your business, products or event through our company channel. These promotion packages include a basic report. The team confirms the post count, content, schedule and quotation for your needs.'),
      ['你们账号', '你们的账号', '公司账号', 'your channel', 'your account', 'company channel', 'company account'], ['everyday', 'reports']),
    entry('everyday', 'xhs', ['everyday'], pair('Everyday 的三篇、五篇是怎么安排的？', 'How are the Everyday three- and five-post plans arranged?'),
      pair('三篇套餐在三个月内完成，五篇套餐在五个月内完成。这是整个套餐的总篇数，不是每月篇数。具体日期共同协调；付费广告不默认包含，也不承诺固定浏览量。',
        'Three posts are delivered over three months, or five posts over five months. These are total package quantities, not monthly allowances. Dates are coordinated. Paid advertising is not included by default, and fixed view counts are not promised.'),
      ['everyday', '三篇', '五篇', '3 posts', '5 posts', 'three posts', 'five posts', '推广周期'], ['upgrade', 'premium']),
    entry('upgrade', 'xhs', ['upgrade'], pair('已经发布的帖子可以计入升级套餐吗？', 'Can an existing post count towards an upgrade?'),
      pair('Everyday 可在三个月升级窗口内，将原帖计入新套餐总篇数。已有一篇时，升级到三篇或五篇，分别剩两篇或四篇。窗口起算日、结束日期和费用抵扣，需要团队书面确认。',
        'Within the three-month Everyday upgrade window, the original post can count towards the new total. One existing post leaves two or four further posts in a three- or five-post plan. The team confirms the window start, end date and payment credit in writing.'),
      ['升级', '原帖', '已发布', 'upgrade', 'previous post', 'existing post'], ['everyday', 'quote']),
    entry('premium', 'xhs', ['premium'], pair('Premium 包含付费推广吗？效果如何确认？', 'Does Premium include paid promotion, and how are results agreed?'),
      pair('Premium 包含平台付费广告。合作前，团队会在书面方案中与你确认推广目标、平台统计口径、评估期限以及未达标时的处理安排。浏览或曝光不等于独立访客、咨询或销售；这里不提供未经确认的效果或退款承诺。',
        'Premium includes paid platform advertising. Before work starts, the team agrees the campaign target, platform metric, assessment window and shortfall arrangements with you in writing. Views or impressions are not unique visitors, enquiries or sales. This page does not make an unconfirmed performance or refund promise.'),
      ['premium', '1000', '1,000', '5000', '5,000', '浏览量', '曝光量', '最低浏览', 'views', 'minimum views'], ['reports', 'refund']),
    entry('reports', 'xhs', ['reports'], pair('发布在你们账号上的推广有报告吗？', 'Does promotion on your channel include a report?'),
      pair('有，包括入门套餐在内，我们账号上的推广套餐都含基础报告，通常发布后约两周提供；其他时间需求可另行商定。这个报告时间不是 Premium 的最终达标期限。',
        'Yes. All promotion tiers on our channel, including entry plans, include a basic report, normally around two weeks after publication unless otherwise agreed. This reporting date is not Premium\'s final performance deadline.'),
      ['报告', '汇报', '两周', 'report', 'reports', 'reporting', 'two weeks'], ['management-reports', 'premium']),
    entry('management-reports', 'xhs', ['reports', 'management'], pair('自己账号的代运营也默认包含同样的报告吗？', 'Does my account-management plan include the same report?'),
      pair('不应直接套用。约两周提供基础报告的统一包含安排，针对发布在我们账号上的推广。你自己账号的代运营，报告内容和频率需要在服务方案中另外确认。',
        'Not automatically. The included basic report at around two weeks applies to promotion on our company channel. Reporting content and frequency for management of your own account need agreement in your service proposal.'),
      ['代运营报告', '报告', '自己账号报告', 'account management report', 'reports', 'reporting'], ['reports', 'management']),
    entry('revisions', 'xhs', ['revisions'], pair('代运营内容可以修改几次？', 'How many revision rounds are included?'),
      pair('在原 brief 或已确认方向内，每篇最多三轮修改。更换方向或增加制作内容，需要先确认新的工作范围，不是无限改稿；具体额外工作和费用由团队事先确认。',
        'Each post allows up to three revision rounds within the original brief or agreed direction. A new direction or added production requires an agreed change of scope. Revisions are not unlimited, and the team confirms any additional work and fees beforehand.'),
      ['修改', '改稿', '三轮', '三次', 'revisions', 'revision', 'changes', 'revise'], ['management', 'delay']),
    entry('delay', 'xhs', ['delay'], pair('我延迟交素材或确认稿件，会怎么处理？', 'What if I am late with materials or approval?'),
      pair('可以灵活协调排期，但客户延误不自动减免月费，延期和结转需双方商定。未回复不等于同意，不会自动发布未确认的稿件。这也不是适用于所有争议的不退款承诺。',
        'We can coordinate a revised schedule, but client delays do not automatically reduce monthly fees. Carryover needs agreement. Silence is not approval, so unapproved drafts are not automatically published. This is not a blanket no-refund policy for every dispute.'),
      ['延误', '延期', '不回复', '自动发', '月费', 'late', 'delay', 'approval', 'monthly fee'], ['revisions', 'refund']),
    entry('materials', 'xhs', ['materials'], pair('图片和视频需要准备多少？', 'How many images or how much video should I prepare?'),
      pair('图文内容通常建议精选 3–10 张图片，这不是平台硬性上限。视频建议简短，完整宣传或教育内容可到两分钟，但不保证用户看完。额外拍摄和制作是否包含，需要先确认。',
        'For a photo post, we generally suggest 3–10 selected images; this is guidance, not a platform limit. Keep videos short. Suitable promotional or educational content may run up to two minutes, without a completion guarantee. Extra filming and production need scoping.'),
      ['图片', '视频', '素材', '拍摄', 'photos', 'images', 'video', 'filming', 'materials'], ['management', 'preparation']),
    entry('audience', 'xhs', ['audience'], pair('推广主要面向哪些人群？', 'Which audiences do you primarily reach?'),
      pair('小红书内容主要面向本地华人社区和留学生，也可考虑与业务相关的国际游客。具体人群和内容会根据你的业务确认；过去的粉丝或曝光数据不是当前效果保证。',
        'Our Xiaohongshu content primarily addresses local Chinese-speaking communities and international students. Relevant international-visitor audiences can also be considered. Content and targeting depend on your business; historical audience figures are not current performance guarantees.'),
      ['华人', '留学生', '游客', '受众', '粉丝', 'students', 'audience', 'tourists', 'followers'], ['local-market', 'xhs-routes']),
    entry('local-market', 'local', ['local-market', 'audience'], pair('Local Market 适合什么业务？', 'What is Local Market promotion for?'),
      pair('适合本地体验、目的地及相关业务，通过我们的频道介绍给华人社区、留学生等相关受众。内容可围绕季节或活动安排。这不是 Google 地图或本地 SEO 服务，也不默认包含付费广告或保证订单；旧 Tourism 套餐已不再销售。',
        'Local Market introduces local experiences, destinations and relevant businesses through our channel, with seasonal or event-led content for relevant Chinese-speaking and student audiences. It is not Google Maps or local SEO, and does not automatically include paid ads or guaranteed bookings. The old Tourism package is retired.'),
      ['local market', '本地市场', '本地体验', '酒庄', '景点', 'tourism', 'winery', 'attractions', 'local experiences'], ['audience', 'seo']),
    entry('website', 'build', ['website'], pair('可以做新网站，也可以改善现有网站吗？', 'Can you build a website or improve my existing one?'),
      pair('都可以。我们可以搭建业务网站，也可以只改善现有网站的内容、体验和咨询入口，不会默认要求整站重做。具体页面、功能和语言范围由团队与你确认。',
        'Yes. We can build a business website or improve the content, experience and enquiry journey of an existing one. A full rebuild is not the default. The team agrees the pages, features and languages with you.'),
      ['网站', '网页', '重做', '预约网站', 'website', 'web design', 'booking website', 'rebuild'], ['bilingual', 'timing']),
    entry('bilingual', 'build', ['bilingual'], pair('可以制作中英文内容吗？', 'Can you help with Chinese and English content?'),
      pair('可以协助中英文网站内容、营销沟通和相关跟进流程。需要哪些双语页面、由谁审稿及后续如何更新，会在方案中说明，不只是逐字翻译。',
        'We can support Chinese and English website content, marketing communication and related follow-up. The proposal defines the bilingual pages, review responsibilities and update arrangements; it is not simply word-for-word translation.'),
      ['双语', '中英文', '翻译', 'bilingual', 'translation', 'chinese and english'], ['website', 'quote']),
    entry('ecommerce', 'build', ['ecommerce'], pair('你们能做电商网站和运营支持吗？', 'Do you support ecommerce websites and operations?'),
      pair('可以协助网店、商品目录、活动页面及从浏览到购买或咨询的路径。具体单次或持续支持，先根据现有平台与权限确认。履约、退款、支付账户操作和第三方费用不默认包含，也不保证销量。',
        'We can help with online stores, product catalogues, campaign pages and the journey to a purchase or enquiry. One-off or ongoing support is scoped around the platform and access. Fulfilment, refunds, payment-account operations and third-party fees are not automatically included; sales are not guaranteed.'),
      ['电商', '网店', '商城', '商品', 'ecommerce', 'e-commerce', 'shopify', 'online store'], ['website', 'integration']),
    entry('app', 'build', ['app'], pair('可以开发 App 并协助上架吗？', 'Can you develop an app and help with its launch?'),
      pair('可以按客户或内部团队的业务需求，规划 Web App、移动应用及约定范围内的上架支持。应用商店决定审核结果和时间，我们不能保证上架；功能、账号责任及维护范围需先确认。',
        'We can scope web or mobile apps for customers or internal teams, including agreed app-store launch support. The store controls approval and review timing, which we cannot guarantee. Features, account responsibilities and maintenance are agreed first.'),
      ['app', 'apps', 'application', 'applications', '应用', '上架', '小程序', 'mobile app', 'app store', 'portal'], ['ownership', 'timing']),
    entry('maintenance', 'build', ['maintenance'], pair('交付后可以继续维护吗？', 'Can you provide support after delivery?'),
      pair('可以讨论持续支持，但托管、域名、第三方订阅和维护不默认包含在所有项目中。具体范围、费用和响应安排会单独说明，不默认承诺全天候支持。',
        'Ongoing support can be discussed, but hosting, domains, third-party subscriptions and maintenance are not automatically included in every project. Scope, fees and response arrangements need agreement; round-the-clock support is not assumed.'),
      ['维护', '托管', '域名', '订阅', 'maintenance', 'hosting', 'domain', 'ongoing support'], ['ownership', 'quote']),
    entry('ownership', 'build', ['ownership'], pair('定制系统的代码和账号归谁？', 'Who owns the code, accounts and data?'),
      pair('账号、代码、数据、权限和交接责任需要在方案中明确。定制系统可以适应你的流程，但不代表第三方组件或服务也归你独占；相关许可和费用会另行说明。',
        'Account, code and data ownership, access and handover responsibilities are agreed in the proposal. A tailored system fits your workflow, but does not automatically make third-party components exclusive to you. Relevant licences and fees need clarification.'),
      ['源码', '代码', '归属', '所有权', 'ownership', 'source code', 'handover'], ['app', 'maintenance']),
    entry('seo', 'build', ['seo'], pair('SEO 能保证很快上 Google 首页吗？', 'Can SEO guarantee a quick first-page ranking?'),
      pair('不能保证固定时间或名次，也不能把收录当作排名或咨询保证。我们可以检查内容、技术可访问性、搜索需求和咨询路径，再根据实际搜索数据安排优化。',
        'No fixed timing or ranking can be guaranteed, and indexing is not a promise of rankings or enquiries. We can review content, technical accessibility, search intent and enquiry journeys, then prioritise work using actual search data.'),
      ['seo', 'google', '排名', '首页', '搜索', 'ranking', 'first page', 'search engine'], ['website', 'local-market']),
    entry('crm', 'automation', ['crm'], pair('咨询容易漏跟进，可以改善吗？', 'Can you help with missed enquiries and follow-up?'),
      pair('可以先梳理咨询进入、负责人分配、跟进和交接流程，再判断改善现有 CRM、连接工具还是定制系统。并不一定需要开发新 App；具体权限和数据迁移另行确认。',
        'We can map how enquiries arrive, get an owner and move through follow-up and handover. That helps determine whether to improve an existing CRM, connect tools or build a system. A new app is not automatically needed; permissions and migration require agreement.'),
      ['crm', '内部系统', '客户管理', '漏单', '漏回复', '漏跟进', '跟进', 'missed enquiries', 'follow-up', 'lead routing'], ['automation', 'integration']),
    entry('automation', 'automation', ['automation'], pair('能搭建自动化流程或简单客服工具吗？', 'Can you build automation or a simple support tool?'),
      pair('可以规划常见问题答复、咨询分流、跟进和营销流程，先确定哪些步骤自动处理、哪些交给团队。网站客服与接管 WhatsApp 或小红书私信不是同一项服务，后者需另查平台接口和授权。',
        'We can scope FAQ tools, enquiry routing, follow-up and marketing workflows, separating automated steps from human decisions. A website help tool is not the same as operating WhatsApp or Xiaohongshu inboxes; those need separate platform and permission checks.'),
      ['自动化', '自动回复', '私信', '机器人', '客服工具', '邮件跟进', 'automation', 'chatbot', 'email automation', 'customer support tool'], ['crm', 'integration']),
    entry('integration', 'automation', ['integration'], pair('现有工具可以保留或连接吗？', 'Can we keep or connect our existing tools?'),
      pair('可以先评估保留现有工具，不默认替换或迁移。是否能进一步对接，取决于接口、账号权限和实际功能，不能只凭工具名称保证兼容。首次沟通不需要提供密码或客户数据库。',
        'We can assess keeping your current tools rather than assuming replacement or migration. Deeper integration depends on APIs, permissions and actual features, not just a tool name. You do not need to share passwords or a customer database for an initial enquiry.'),
      ['对接', '连接', 'api', '迁移', '保留工具', 'integration', 'connect tools', 'existing tools', 'booking tool'], ['crm', 'website']),
    entry('quote', 'working', ['quote'], pair('套餐和项目怎么报价？', 'How do I get a package or project quotation?'),
      pair('这里不公开套餐价格。费用根据服务范围、内容或功能、周期和后续支持确认。通过 WhatsApp 告诉我们你的业务和想解决的问题，团队会与你确认范围后报价，不必先准备完整方案或预算。',
        'Package prices are not published here. Fees depend on scope, content or features, timing and ongoing support. Tell us about your business and goal on WhatsApp; the team will clarify the scope and provide a quotation. A complete specification or budget is not required.'),
      ['多少钱', '价格', '报价', '收费', '费用', '套餐价格', '预算', '优惠', 'price', 'pricing', 'cost', 'quote', 'quotation', 'fees', 'budget'], ['preparation', 'timing']),
    entry('timing', 'working', ['quote', 'website', 'app'], pair('项目通常需要多久？', 'How long would my project take?'),
      pair('需要先确认工作范围、素材、账号权限和排期，再由团队给出时间安排。网站、App 和系统搭建不能套用小红书套餐周期，这里不承诺未经确认的交付日期。',
        'The team can propose a schedule after confirming scope, materials, access and availability. Website, app and system work do not follow Xiaohongshu package durations. We do not promise an unconfirmed delivery date here.'),
      ['多久', '工期', '交付', '多长时间', 'how long', 'timeline', 'turnaround', 'delivery date'], ['everyday', 'preparation']),
    entry('preparation', 'working', ['quote', 'integration'], pair('第一次咨询需要准备什么？', 'What should I prepare for a first enquiry?'),
      pair('简单说明业务类型、目标地区、目前遇到的问题和已有工具即可。没有完整 brief 也可以联系。不需要在这里填写客户资料、密码或上传保密文件；后续需要的资料由团队与你另行确认。',
        'A short description of your business, target area, current problem and existing tools is enough to begin. You can enquire without a complete brief. Do not enter customer records, passwords or confidential files here; the team will agree any further information needed.'),
      ['准备', '开始合作', 'brief', '第一次', 'prepare', 'first enquiry', 'get started'], ['quote', 'confidentiality']),
    entry('confidentiality', 'working', ['confidentiality'], pair('可以看看你们做过的案例吗？', 'Can I see examples of your work?'),
      pair('部分项目受保密协议约束，不能在这里公开客户名称、截图或资料。联系团队后，可以在协议和授权允许的范围内介绍部分相关案例，并非所有项目都能展示；历史表现也不是未来效果保证。',
        'Some work is covered by confidentiality agreements, so client names, screenshots and material are not shown here. The team may discuss relevant examples privately where agreements and permissions allow. Not every project can be shown, and past performance is not a forecast.'),
      ['案例', '作品', '保密', '截图', '客户名单', 'case studies', 'portfolio', 'showcase', 'nda', 'confidential'], ['preparation', 'overview']),
    entry('refund', 'working', ['refund', 'reports'], pair('未达标、退款或已有项目问题怎么处理？', 'Who handles shortfalls, refunds or an existing project issue?'),
      pair('请直接联系团队，根据实际协议、交付情况和适用权利处理。这个常见问题页面不能决定或办理退款。推广的两周报告时间不等于最终达标期限。',
        'Please contact the team to review the agreement, work delivered and applicable rights. This FAQ cannot determine or process refunds. The two-week promotion report is not the final performance deadline.'),
      ['退款', '不达标', '未达标', '退一半', '退钱', '赔偿', '投诉', 'refund', 'shortfall', 'complaint', 'compensation'], ['premium', 'reports'])
  ];
  window.GoMarketingHelp = Object.freeze({version: '2026-10-06-public-1', publicationApproved: true,
    categories, entries, popular: ['xhs-routes', 'quote', 'website', 'crm', 'app', 'confidentiality'],
    contacts: {whatsapp: 'https://wa.me/61450428693', email: 'mailto:info@gomarketing.net.au', phone: 'tel:+61299096785'}});
})();
